spring:
  thymeleaf:
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  application:
    name: dld-apa
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #// 192.168.0.119
    url: jdbc:mysql://localhost:3306/laola?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 8081
  max-http-header-size: 102400
mybatis:
  type-aliases-package: com.laola.hello.laola.entity
  mapper-locations: classpath:mapper/*.xml

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#github token a07233876e043761d4db8d04231bdb6f1ec9388f